### ISSUE TITLE
Fix email templates.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Ono-Music-Site#1]
Templates contain `\n` instead of actual line feeds. I suspect this is due to import bug of sorts, but none the less needs to be fixed anyway. SendGrid is configured and mailing check should be done.

**Comment by iliyaM** [comment]
fixed and configured. i need real information for the client.

**Comment by MeanEYE** [comment]
@hanan-avzuk can you provide real info from the client for mailing.
